version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGO_URI: ${MONGO_URI}
        API_SECRET: ${API_SECRET}
    container_name: api-container-new
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
      - API_SECRET=${API_SECRET}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    container_name: mongo-container-new
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
